import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const categorias = [
    'Lanches',
    'Pizzas',
    'Japonesa',
    'Brasileira',
    'Hamburguer',
    'Bebidas',
    'Doces & Bolos',
    'Sorvetes',
    'Açaí',
    'Marmita',
    'Saudável',
    'Padaria',
    'Mercado',
    'Farmácia',
    'Pet',
    'Vegetariana',
    'Vegana',
    'Chinesa',
    'Árabe',
    'Italiana',
    'Frutos do Mar',
    'Massas',
    'Cafeteria',
    'Cervejaria',
    'Comida Mexicana',
    'Comida Indiana',
    'Comida Francesa',
    'Comida Alemã',
    'Comida Coreana',
    'Comida Tailandesa',
    'Comida Portuguesa',
    'Comida Grega',
    'Comida Turca',
    'Comida Peruana',
    'Comida Espanhola',
    'Comida Africana',
    'Comida Contemporânea',
    'Comida Internacional',
    'Comida Orgânica',
    'Comida Natural',
    'Comida de Boteco',
    'Churrasco',
    'Peixes',
    'Salgados',
    'Caldos',
    'Creperia',
    'Tapiocaria',
    'Temakeria',
    'Sushi',
    'Hot Dog',
    'Esfiha',
    'Pastel',
    'Pizza Doce',
    'Poke',
    'Massa Artesanal',
    'Comida Mineira',
    'Comida Nordestina',
    'Comida Goiana',
    'Comida Paraense',
    'Comida Baiana',
    'Comida Gaúcha',
    'Comida Amazônica',
    'Comida Paranaense',
    'Comida Catarinense',
    'Comida Capixaba',
    'Comida Paulista',
    'Comida Carioca',
    'Comida Matogrossense',
    'Comida Matogrossense do Sul',
    'Comida Rondoniense',
    'Comida Acreana',
    'Comida Tocantinense',
    'Comida Piauiense',
    'Comida Maranhense',
    'Comida Sergipana',
    'Comida Alagoana',
    'Comida Potiguar',
    'Comida Paraibana',
    'Comida Pernambucana',
    'Comida Cearense',
    'Comida Amazonense',
    'Comida Roraimense',
    'Comida Amapaense',
    'Comida Brasiliense',
    'Comida Sulista',
    'Comida Sudestina',
    'Comida Norte',
    'Comida Centro-Oeste',
    'Comida Litorânea',
    'Comida Sertaneja',
    'Comida Caipira',
    'Comida de Rua',
    'Comida de Festa',
    'Comida de Praia',
    'Comida de Inverno',
    'Comida de Verão',
    'Comida de Natal',
    'Comida de Páscoa',
    'Comida de Ano Novo',
    'Comida de Carnaval',
    'Comida de São João',
    'Comida de Halloween',
    'Comida de Dia das Mães',
    'Comida de Dia dos Pais',
    'Comida de Dia das Crianças',
    'Comida de Dia dos Namorados',
    'Comida de Dia das Mulheres',
    'Comida de Dia dos Avós',
    'Comida de Dia dos Professores',
    'Comida de Dia do Trabalho',
    'Comida de Dia da Independência',
    'Comida de Dia da República',
    'Comida de Dia da Consciência Negra',
    'Comida de Dia do Índio',
    'Comida de Dia do Amigo',
    'Comida de Dia do Cliente',
    'Comida de Dia do Consumidor',
    'Comida de Dia do Comerciário',
    'Comida de Dia do Agricultor',
    'Comida de Dia do Padeiro',
    'Comida de Dia do Açougueiro',
    'Comida de Dia do Feirante',
    'Comida de Dia do Cozinheiro',
    'Comida de Dia do Garçom',
    'Comida de Dia do Chef',
    'Comida de Dia do Barista',
    'Comida de Dia do Sommelier',
    'Comida de Dia do Barman',
    'Comida de Dia do Churrasqueiro',
    'Comida de Dia do Pizzaiolo',
    'Comida de Dia do Sushi Man',
    'Comida de Dia do Temaki Man',
    'Comida de Dia do Sushiman',
    'Comida de Dia do Temakiman',
    'Comida de Dia do Padeiro',
    'Comida de Dia do Confeiteiro',
    'Comida de Dia do Sorveteiro',
    'Comida de Dia do Açaizeiro',
    'Comida de Dia do Marmiteiro',
    'Comida de Dia do Salgadeiro',
    'Comida de Dia do Caldeiro',
    'Comida de Dia do Crepeiro',
    'Comida de Dia do Tapiocaria',
    'Comida de Dia do Hot Dogueiro',
    'Comida de Dia do Esfiharia',
    'Comida de Dia do Pastelaria',
    'Comida de Dia do Pizzaria',
    'Comida de Dia do Poke',
    'Comida de Dia do Massa Artesanal',
    'Comida de Dia do Churrascaria',
    'Comida de Dia do Peixaria',
    'Comida de Dia do Salgaderia',
    'Comida de Dia do Caldeirada',
    'Comida de Dia do Creperia',
    'Comida de Dia do Tapiocaria',
    'Comida de Dia do Temakeria',
    'Comida de Dia do Sushieria',
    'Comida de Dia do Hot Dogueria',
    'Comida de Dia do Esfiharia',
    'Comida de Dia do Pastelaria',
    'Comida de Dia do Pizza Doce',
    'Comida de Dia do Poke',
    'Comida de Dia do Massa Artesanal',
  ];

  for (const nome of categorias) {
    await prisma.categoria.upsert({
      where: { nome },
      update: {},
      create: { nome },
    });
  }

  console.log('Categorias populadas com sucesso!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
